name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ARM64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          tags: dsh:arm64
          outputs: type=docker,dest=/tmp/dsh-arm64.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: dsh-arm64
          path: /tmp/dsh-arm64.tar
          retention-days: 7
